<?php

namespace Database\Seeders\Business\Tours;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class DestinationSeeder extends Seeder
{
    public function run(): void
    {
        $destinations = [

            // ===================== NEPAL (1) =====================
            [
                'name' => 'Kathmandu',
                'country_id' => 1,
                'short_description' => 'The cultural and historical heart of Nepal.',
                'content' => 'Kathmandu, the vibrant capital of Nepal, is a city where ancient history, living traditions, and everyday life blend together in a way few places on Earth can match. Nestled in the Kathmandu Valley and surrounded by rolling green hills, the city has been a cultural and spiritual heart of the Himalayas for more than two thousand years. Every street, courtyard, and temple tells a story, making Kathmandu feel less like a single city and more like a living museum that continues to breathe and evolve.',
                'type' => 'city',
                'keywords' => 'tour',
                'latitude' => '27.7172',
                'longitude' => '85.3240',
                'cover_image' => 'tours/destinations/kathmandu/2.jpg',
                'images' => [
                    'tours/destinations/kathmandu/1.jpg',
                    'tours/destinations/kathmandu/2.jpg',
                    'tours/destinations/kathmandu/3.webp',
                    'tours/destinations/kathmandu/4.webp',
                    'tours/destinations/kathmandu/5.jpg',
                ],
                'is_featured' => true,
            ],
            [
                'name' => 'Pokhara',
                'country_id' => 1,
                'short_description' => 'A scenic city of lakes and mountains.',
                'content' => 'Pokhara, one of Nepal’s most beautiful and peaceful cities, is a place where natural beauty and relaxed mountain life come together effortlessly. Set beside the tranquil Phewa Lake and framed by the towering Annapurna range, the city has long been a favorite destination for travelers seeking both adventure and serenity. With its fresh air, open landscapes, and slower pace, Pokhara feels like a gentle escape from the rush of everyday life. <br><br> For centuries, Pokhara has served as a gateway to the Himalayas, welcoming trekkers, pilgrims, and explorers from around the world. At the same time, its lakeside paths, colorful cafés, and surrounding hills create a soothing atmosphere that invites visitors to slow down, reflect, and connect with nature. Every sunrise over the mountains and every quiet walk along the water adds to Pokhara’s timeless charm, making it not just a destination, but a feeling that stays with you long after you leave.',
                'type' => 'city',
                'latitude' => '28.2096',
                'keywords' => 'tour',
                'longitude' => '83.9856',
                'cover_image' => 'tours/destinations/pokhara/2.jpg',
                'images' => [
                    'tours/destinations/pokhara/1.jpg',
                    'tours/destinations/pokhara/2.jpg',
                    'tours/destinations/pokhara/3.jpg',
                    'tours/destinations/pokhara/4.jpg',
                    'tours/destinations/pokhara/5.jpg',
                ],
                'is_featured' => true,
            ],
            [
                'name' => 'Everest Base Camp',
                'country_id' => 1,
                'keywords' => 'tour',

                'short_description' => 'World-famous trekking destination.',
                'content' => 'Everest Base Camp, the legendary gateway to the world’s highest peak, is a destination that captures the spirit of adventure like no other place on Earth. Set high in the Khumbu region of Nepal and surrounded by towering हिमालयन giants, it has drawn trekkers, climbers, and dreamers for decades. The journey to Everest Base Camp is not just about reaching a point on the map, but about experiencing the raw beauty, scale, and power of the Himalayas step by step.
    <br><br>
Along the trail, ancient monasteries, prayer flags, and stone-built Sherpa villages reflect a deep connection between nature, culture, and faith. The path winds through dramatic valleys, glacial rivers, and rugged mountain landscapes, offering breathtaking views at every turn. Standing at Everest Base Camp, with icefalls stretching ahead and peaks rising all around, is a humbling and unforgettable moment — one that represents perseverance, respect for the mountains, and the timeless human desire to explore beyond limits.',
                'type' => 'adventure',
                'latitude' => '28.0026',
                'longitude' => '86.8528',
                'cover_image' => 'tours/destinations/everest/3.jpg',
                'images' => [
                    'tours/destinations/everest/1.webp',
                    'tours/destinations/everest/2.jpg',
                    'tours/destinations/everest/3.jpg',
                    'tours/destinations/everest/4.jpeg',
                    'tours/destinations/everest/5.webp',
                ],
                'is_featured' => true,
            ],
            [
                'name' => 'Lumbini',
                'country_id' => 1,
                'keywords' => 'tour',

                'short_description' => 'Birthplace of Lord Buddha.',
                'content' => 'Lumbini, the sacred birthplace of Lord Buddha, is one of the most peaceful and spiritually significant destinations in the world. Located in the southern plains of Nepal, this serene site has been a center of pilgrimage and reflection for over two thousand years. More than just a historical location, Lumbini offers a quiet space where history, faith, and inner calm come together in harmony.
<br><br>
At the heart of Lumbini lies the Maya Devi Temple, marking the exact spot where Siddhartha Gautama was born, surrounded by ancient ruins, monastic gardens, and tranquil ponds. Monasteries built by different nations line the peaceful pathways, each reflecting unique architectural and cultural interpretations of Buddhist tradition. Walking through Lumbini feels slow and meditative, inviting visitors to pause, reflect, and reconnect with a deeper sense of mindfulness and compassion.',
                'type' => 'heritage',
                'latitude' => '27.4844',
                'longitude' => '83.2760',
                'cover_image' => 'tours/destinations/lumbini/2.jpg',
                'images' => [
                    'tours/destinations/lumbini/1.jpg',
                    'tours/destinations/lumbini/2.jpg',
                    'tours/destinations/lumbini/3.jpg',
                    'tours/destinations/lumbini/4.jpg',
                    'tours/destinations/lumbini/5.jpg',
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'Chitwan National Park',
                'country_id' => 1,
                'keywords' => 'tour',

                'short_description' => 'Wildlife safari destination.',
                'content' => 'Chitwan, located in the lush lowlands of southern Nepal, is a destination where rich wildlife, natural beauty, and local culture come together in perfect balance. Best known for Chitwan National Park, Nepal’s first national park and a UNESCO World Heritage Site, the region offers a rare chance to experience the country’s wild side. Dense forests, winding rivers, and open grasslands create a landscape that feels worlds away from the mountains.
<br><br>
Chitwan is home to an incredible variety of wildlife, including the one-horned rhinoceros, Bengal tiger, elephants, and hundreds of bird species. Visitors can explore the park through jungle safaris, canoe rides, and guided nature walks, while nearby Tharu villages offer insight into the traditions and lifestyle of the region’s indigenous people. With its peaceful surroundings and close connection to nature, Chitwan provides a refreshing escape and a deeper appreciation of Nepal’s diverse landscapes beyond the Himalayas.',
                'type' => 'wildlife',
                'latitude' => '27.5291',
                'longitude' => '84.3542',
                'cover_image' => 'tours/destinations/lumbini/2.jpg',
                'images' => [
                    'tours/destinations/lumbini/1.jpg',
                    'tours/destinations/lumbini/2.jpg',
                    'tours/destinations/lumbini/3.jpg',
                    'tours/destinations/lumbini/4.jpg',
                    'tours/destinations/lumbini/5.webp',
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'Annapurna Base Camp',
                'country_id' => 1,
                'keywords' => 'tour',

                'short_description' => 'Popular Himalayan trekking route.',
                'content' => 'The Annapurna region is one of Nepal’s most iconic and diverse trekking destinations, offering an extraordinary blend of towering Himalayan peaks, traditional mountain villages, and ever-changing landscapes. Dominated by the Annapurna mountain range, which includes some of the world’s highest peaks, the region has captivated trekkers and nature lovers for generations. Every trail reveals dramatic scenery, from deep river valleys to high alpine terrain, making the journey as rewarding as the destination itself.
<br></br>
Beyond its natural beauty, Annapurna is rich in culture and daily mountain life. Ancient monasteries, prayer flags, and stone houses line the routes, while communities of Gurung, Magar, and Thakali people welcome visitors with warm hospitality. Whether trekking through lush forests, crossing high mountain passes, or standing beneath snow-covered summits, the Annapurna experience offers a powerful connection to nature, culture, and the timeless spirit of the Himalayas.',
                'type' => 'adventure',
                'latitude' => '28.5312',
                'longitude' => '83.8780',
                'cover_image' => 'tours/destinations/annapurna/3.jpg',
                'images' => [
                    'tours/destinations/annapurna/1.jpg',
                    'tours/destinations/annapurna/2.webp',
                    'tours/destinations/annapurna/3.jpg',
                    'tours/destinations/annapurna/4.jpg',
                    'tours/destinations/annapurna/5.jpg',
                ],
                'is_featured' => false,
            ],

            // ===================== INDIA (2) =====================
            [
                'name' => 'Delhi',
                'country_id' => 2,
                'keywords' => 'tour',

                'short_description' => 'Capital city with rich history.',
                'content' => 'Delhi, the capital of India, is a city where ancient history and modern life exist side by side. With a past shaped by powerful dynasties and empires, the city is home to grand monuments, historic mosques, bustling markets, and wide colonial-era avenues. From centuries-old forts to lively streets filled with everyday energy, Delhi offers a deep and immersive introduction to India’s cultural and historical richness.',
                'type' => 'city',
                'latitude' => '28.6139',
                'longitude' => '77.2090',
                'cover_image' => 'tours/destinations/delhi/3.jpg',
                'images' => [
                    'tours/destinations/delhi/1.jpg',
                    'tours/destinations/delhi/2.webp',
                    'tours/destinations/delhi/3.jpg',
                    'tours/destinations/delhi/4.jpg',
                    'tours/destinations/delhi/5.jpg',
                ],
                'is_featured' => true,
            ],
            [
                'name' => 'Agra',
                'country_id' => 2,
                'keywords' => 'tour',

                'short_description' => 'Home of the Taj Mahal.',
                'content' => 'Agra is a city defined by timeless beauty and Mughal grandeur, best known as the home of the iconic Taj Mahal. Set along the banks of the Yamuna River, Agra reflects an era of architectural brilliance and imperial elegance. Beyond the Taj Mahal, historic forts and tombs reveal stories of love, power, and legacy, making Agra a deeply memorable destination rooted in history and emotion.',
                'type' => 'heritage',
                'latitude' => '27.1767',
                'longitude' => '78.0081',
                'cover_image' => 'tours/destinations/agra/2.jpg',
                'images' => [
                    'tours/destinations/agra/1.jpg',
                    'tours/destinations/agra/2.jpg',
                    'tours/destinations/agra/3.jpg',
                    'tours/destinations/agra/4.jpg',
                    'tours/destinations/agra/5.jpg',
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'Jaipur',
                'country_id' => 2,
                'keywords' => 'tour',

                'short_description' => 'The Pink City of India.',
                'content' => 'Jaipur, the Pink City of Rajasthan, is a vibrant destination celebrated for its royal heritage, colorful streets, and striking architecture. Majestic forts, elegant palaces, and lively bazaars showcase the grandeur of Rajput culture and tradition. With its warm hues, rich craftsmanship, and welcoming atmosphere, Jaipur offers a perfect blend of history, culture, and everyday life.',
                'type' => 'heritage',
                'latitude' => '26.9124',
                'longitude' => '75.7873',
                'cover_image' => 'tours/destinations/jaipur/3.jpg',
                'images' => [
                    'tours/destinations/jaipur/1.jpg',
                    'tours/destinations/jaipur/2.webp',
                    'tours/destinations/jaipur/3.jpg',
                    'tours/destinations/jaipur/4.jpg',
                    'tours/destinations/jaipur/5.jpg',
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'Goa',
                'country_id' => 2,
                'keywords' => 'tour',

                'short_description' => 'Beach paradise of India.',
                'content' => 'Goa is India’s most relaxed and vibrant coastal destination, known for its golden beaches, laid-back lifestyle, and unique blend of cultures. Shaped by centuries of Portuguese influence, the region offers a mix of scenic coastlines, historic churches, lively markets, and beachside villages. Whether enjoying peaceful sunsets by the sea or exploring its rich heritage and local flavors, Goa provides a perfect balance of leisure, culture, and natural beauty.',
                'type' => 'beach',
                'latitude' => '15.2993',
                'longitude' => '74.1240',
                'cover_image' => 'tours/destinations/goa/2.avif',
                'images' => [
                    'tours/destinations/goa/1.jpg',
                    'tours/destinations/goa/2.avif',
                    'tours/destinations/goa/3.jpg',
                    'tours/destinations/goa/4.avif',
                    'tours/destinations/goa/5.jpg',
                ],
                'is_featured' => true,
            ],
            [
                'name' => 'Kerala',
                'country_id' => 2,
                'keywords' => 'tour',

                'short_description' => 'God’s Own Country.',
                'content' => 'Kerala, often called “God’s Own Country,” is a land of lush landscapes, tranquil backwaters, and deep-rooted traditions. Located along India’s southwestern coast, the region is known for its palm-lined waterways, misty hill stations, and rich biodiversity. From peaceful houseboat journeys to vibrant cultural practices and wellness traditions, Kerala offers a refreshing and deeply relaxing travel experience connected closely with nature.',
                'type' => 'hill',
                'latitude' => '10.8505',
                'longitude' => '76.2711',
                'cover_image' => 'tours/destinations/kerala/2.jpg',
                'images' => [
                    'tours/destinations/kerala/1.jpg',
                    'tours/destinations/kerala/2.jpg',
                    'tours/destinations/kerala/3.jpeg',
                    'tours/destinations/kerala/4.jpg',
                    'tours/destinations/kerala/5.avif',
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'Varanasi',
                'country_id' => 2,
                'keywords' => 'tour',

                'short_description' => 'Spiritual capital of India.',
                'content' => 'Varanasi, one of the world’s oldest continuously inhabited cities, is the spiritual heart of India. Situated along the sacred Ganges River, the city is a powerful center of faith, rituals, and philosophy. Ancient temples, riverside ghats, and daily ceremonies create an atmosphere filled with devotion and reflection. Visiting Varanasi is not just about sightseeing—it is an experience that reveals the depth of spirituality, tradition, and timeless human belief.',
                'type' => 'heritage',
                'latitude' => '25.3176',
                'longitude' => '82.9739',
                'cover_image' => 'tours/destinations/varanasi/2.jpg',
                'images' => [
                    'tours/destinations/varanasi/1.jpg',
                    'tours/destinations/varanasi/2.jpg',
                    'tours/destinations/varanasi/3.jpg',
                    'tours/destinations/varanasi/4.jpg',
                    'tours/destinations/varanasi/5.jpg',
                ],
                'is_featured' => false,
            ],

            // ===================== BHUTAN (3) =====================
            [
                'name' => 'Paro',
                'country_id' => 3,
                'keywords' => 'tour',

                'short_description' => 'Gateway to Bhutan.',
                'content' => 'Paro, nestled in a verdant valley in western Bhutan, is a harmonious blend of natural beauty and cultural heritage. Known for its dramatic landscapes, Paro is dotted with terraced rice fields, flowing rivers, and traditional Bhutanese architecture. The town is home to the iconic Paro Taktsang (Tiger’s Nest Monastery), perched precariously on a cliff, offering breathtaking views and spiritual serenity. Visitors can enjoy peaceful hikes, vibrant local festivals, and a deep connection to Bhutanese traditions in this enchanting valley.',
                'type' => 'heritage',
                'latitude' => '27.4305',
                'longitude' => '89.4136',
                'cover_image' => 'tours/destinations/bhutan/2.jpg',
                'images' => [
                    'tours/destinations/bhutan/1.jpg',
                    'tours/destinations/bhutan/2.jpg',
                    'tours/destinations/bhutan/3.jpg',
                    'tours/destinations/bhutan/4.jpg',
                    'tours/destinations/bhutan/5.jpg',
                ],
                'is_featured' => true,
            ],
            [
                'name' => 'Thimphu',
                'country_id' => 3,
                'keywords' => 'tour',

                'short_description' => 'Capital city of Bhutan.',
                'content' => 'Thimphu, the capital city of Bhutan, beautifully balances modernity and tradition amidst the Himalayas. It is a hub of cultural richness, featuring grand dzongs, bustling markets, and serene temples. Visitors can witness Bhutanese art, music, and crafts while exploring scenic trails and viewpoints that offer sweeping vistas of the Thimphu Valley. With its warm hospitality, sacred sites, and lively cultural scene, Thimphu invites travelers into a unique journey of discovery and spiritual reflection.',
                'type' => 'city',
                'latitude' => '27.4728',
                'longitude' => '89.6390',
                'cover_image' => 'tours/destinations/thimpu/4.jpg',
                'images' => [
                    'tours/destinations/thimpu/1.webp',
                    'tours/destinations/thimpu/2.jpg',
                    'tours/destinations/thimpu/3.jpg',
                    'tours/destinations/thimpu/4.jpg',
                    'tours/destinations/thimpu/5.avif',
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'Punakha',
                'country_id' => 3,
                'keywords' => 'tour',

                'short_description' => 'Historic valley town.',
                'content' => 'Punakha, the former capital of Bhutan, is a picturesque valley renowned for its rivers, lush fields, and majestic dzongs. The Punakha Dzong, a fortress of stunning architecture, sits at the confluence of the Pho Chhu and Mo Chhu rivers, epitomizing Bhutanese elegance. Surrounded by serene landscapes, vibrant flora, and quaint villages, Punakha offers peaceful walks, river rafting adventures, and glimpses of traditional festivals, making it a haven for nature lovers and culture enthusiasts alike.',
                'type' => 'heritage',
                'latitude' => '27.5916',
                'longitude' => '89.8770',
                'cover_image' => 'tours/destinations/punakha/2.jpg',
                'images' => [
                    'tours/destinations/punakha/1.jpg',
                    'tours/destinations/punakha/2.jpg',
                    'tours/destinations/punakha/3.jpg',
                    'tours/destinations/punakha/4.jpg',
                    'tours/destinations/punakha/5.jpg',
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'Bumthang',
                'country_id' => 3,
                'keywords' => 'tour',

                'short_description' => 'Spiritual heartland of Bhutan.',
                'content' => 'Bumthang, often called the spiritual heart of Bhutan, is a cluster of valleys rich in ancient monasteries, sacred sites, and rolling meadows. Renowned for its pristine natural beauty, the region boasts alpine landscapes, apple orchards, and tranquil rivers. Visitors can explore centuries-old temples, hike through scenic trails, and participate in vibrant local festivals, experiencing a harmonious blend of spirituality, culture, and unspoiled nature in this serene Himalayan enclave.',
                'type' => 'heritage',
                'latitude' => '27.6418',
                'longitude' => '90.6773',
                'cover_image' => 'tours/destinations/bumthang/4.jpg',
                'images' => [
                    'tours/destinations/bumthang/1.jpg',
                    'tours/destinations/bumthang/2.avif',
                    'tours/destinations/bumthang/3.avif',
                    'tours/destinations/bumthang/4.jpg',
                    'tours/destinations/bumthang/5.webp',
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'Phobjikha Valley',
                'country_id' => 3,
                'keywords' => 'tour',

                'short_description' => 'Beautiful glacial valley.',
                'content' => 'Phobjikha Valley, a vast glacial valley in central Bhutan, is famous for its serene landscapes, sweeping wetlands, and wintering black-necked cranes. The valley exudes tranquility, with gently rolling hills, traditional villages, and rich biodiversity. Visitors can enjoy nature walks, birdwatching, and visits to Gangtey Monastery, immersing themselves in the quiet rhythms of rural Bhutan while witnessing one of the country’s most iconic natural spectacles.',
                'type' => 'hill',
                'latitude' => '27.4486',
                'longitude' => '90.1860',
                'cover_image' => 'tours/destinations/phobjikha/4.avif',
                'images' => [
                    'tours/destinations/phobjikha/1.avif',
                    'tours/destinations/phobjikha/2.jpg',
                    'tours/destinations/phobjikha/3.jpg',
                    'tours/destinations/phobjikha/4.avif',
                    'tours/destinations/phobjikha/5.webp',
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'Haa Valley',
                'country_id' => 3,
                'keywords' => 'tour',

                'short_description' => 'Remote scenic valley.',
                'content' => 'Haa Valley, tucked away in western Bhutan, is a pristine destination of dramatic mountains, terraced fields, and peaceful rivers. Known for its authentic rural charm, the valley offers glimpses of traditional Bhutanese life, ancient temples, and vibrant local festivals. With its calm surroundings, scenic trekking paths, and rich cultural heritage, Haa Valley is perfect for travelers seeking solitude, natural beauty, and a deep connection with Bhutan’s untouched landscapes.',
                'type' => 'hill',
                'latitude' => '27.3875',
                'longitude' => '89.2807',
                'cover_image' => 'tours/destinations/haa/2.webp',
                'images' => [
                    'tours/destinations/haa/1.jpg',
                    'tours/destinations/haa/2.webp',
                    'tours/destinations/haa/3.jpg',
                    'tours/destinations/haa/4.jpg',
                    'tours/destinations/haa/5.jpg',
                ],
                'is_featured' => false,
            ],

            // ===================== TIBET (4) =====================
            [
                'name' => 'Lhasa',
                'country_id' => 4,
                'keywords' => 'tour',

                'short_description' => 'Spiritual capital of Tibet.',
                'content' => 'Lhasa, the spiritual and cultural heart of Tibet, is a city where history, religion, and breathtaking landscapes converge. Dominated by the majestic Potala Palace, Lhasa is a hub of Tibetan Buddhism, with monasteries, temples, and prayer flags coloring the cityscape. Wandering its streets, visitors encounter bustling markets, sacred sites, and serene corners for reflection, all set against the backdrop of the surrounding Himalayan peaks. Lhasa offers a deeply spiritual and culturally immersive journey.',
                'type' => 'heritage',
                'latitude' => '29.6520',
                'longitude' => '91.1721',
                'cover_image' => 'tours/destinations/lhasa/3.jpg',
                'images' => [
                    'tours/destinations/lhasa/1.jpg',
                    'tours/destinations/lhasa/2.jpg',
                    'tours/destinations/lhasa/3.jpg',
                    'tours/destinations/lhasa/4.webp',
                    'tours/destinations/lhasa/5.jpeg',
                ],
                'is_featured' => true,
            ],
            [
                'name' => 'Potala Palace',
                'country_id' => 4,
                'keywords' => 'tour',

                'short_description' => 'Iconic palace and UNESCO site.',
                'content' => 'Patola is a serene region characterized by rolling hills, traditional Tibetan villages, and rich cultural heritage. Life here flows gently along ancient paths, monasteries, and prayer wheels, inviting visitors to witness the timeless rhythms of Tibetan life. With its pristine landscapes and deep spiritual roots, Patola offers an authentic experience of Tibet’s untouched beauty and sacred traditions.',
                'type' => 'heritage',
                'latitude' => '29.6578',
                'longitude' => '91.1175',
                'cover_image' => 'tours/destinations/patola/3.jpeg',
                'images' => [
                    'tours/destinations/patola/1.webp',
                    'tours/destinations/patola/2.jpg',
                    'tours/destinations/patola/3.jpeg',
                    'tours/destinations/patola/4.webp',
                    'tours/destinations/patola/5.avif',
                ],
                'is_featured' => true,
            ],
            [
                'name' => 'Yamdrok Lake',
                'country_id' => 4,
                'keywords' => 'tour',

                'short_description' => 'Sacred turquoise lake.',
                'content' => 'Yamdrok Lake, one of Tibet’s most stunning natural treasures, gleams turquoise against the surrounding snow-capped mountains. Its vast, mirror-like surface reflects the sky, mountains, and scattered pastoral settlements, creating an almost surreal landscape. Visitors can enjoy serene walks along its shores, connect with local herders, and feel the lake’s tranquil energy, making it a perfect spot for contemplation and nature’s splendor.',
                'type' => 'hill',
                'latitude' => '28.9316',
                'longitude' => '90.9784',
                'cover_image' => 'tours/destinations/yamdrok/3.webp',
                'images' => [
                    'tours/destinations/yamdrok/1.avif',
                    'tours/destinations/yamdrok/2.jpg',
                    'tours/destinations/yamdrok/3.webp',
                    'tours/destinations/yamdrok/4.jpg',
                    'tours/destinations/yamdrok/5.jpg',
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'Mount Kailash',
                'country_id' => 4,
                'keywords' => 'tour',

                'short_description' => 'Sacred mountain pilgrimage.',
                'content' => 'Mount Kailash, the sacred peak revered in Hinduism, Buddhism, Jainism, and Bon, rises dramatically in the western Tibetan plateau. Its snow-capped summit, pristine slopes, and spiritual significance draw pilgrims from around the world. Trekking around the mountain offers breathtaking vistas, a profound sense of devotion, and a connection to the ancient spiritual traditions that have honored this peak for millennia.',
                'type' => 'heritage',
                'latitude' => '31.0675',
                'longitude' => '81.3119',
                'cover_image' => 'tours/destinations/kailash/3.webp',
                'images' => [
                    'tours/destinations/kailash/1.jpg',
                    'tours/destinations/kailash/2.jpg',
                    'tours/destinations/kailash/3.webp',
                    'tours/destinations/kailash/4.jpg',
                    'tours/destinations/kailash/5.jpg',
                ],
                'is_featured' => true,
            ],
            [
                'name' => 'Namtso Lake',
                'country_id' => 4,
                'keywords' => 'tour',

                'short_description' => 'Highest saltwater lake in the world.',
                'content' => 'Namtso Lake, the “Heavenly Lake,” captivates with its crystalline waters and high-altitude serenity. Surrounded by rugged mountains and dotted with monasteries, the lake offers a pristine escape into Tibet’s natural and spiritual landscapes. Visitors can witness the stunning reflections of the sky, explore its sacred shores, and experience a peaceful retreat in one of the region’s most iconic natural wonders.',
                'type' => 'hill',
                'latitude' => '30.7090',
                'longitude' => '90.9819',
                'cover_image' => 'tours/destinations/namtso/2.jpg',
                'images' => [
                    'tours/destinations/namtso/1.jpg',
                    'tours/destinations/namtso/2.jpg',
                    'tours/destinations/namtso/3.jpg',
                    'tours/destinations/namtso/4.jpg',
                    'tours/destinations/namtso/5.webp',
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'Shigatse',
                'country_id' => 4,
                'keywords' => 'tour',

                'short_description' => 'Second-largest city in Tibet.',
                'content' => 'Shigatse, Tibet’s second-largest city, is a blend of cultural depth and historical significance. Home to the magnificent Tashilhunpo Monastery, the seat of the Panchen Lama, Shigatse offers glimpses of grand Buddhist architecture, bustling markets, and traditional Tibetan life. Visitors can explore sacred sites, encounter local traditions, and experience the vibrant energy of a city steeped in spirituality amidst the vast Himalayan backdrop.',
                'type' => 'city',
                'latitude' => '29.2670',
                'longitude' => '88.8806',
                'cover_image' => 'tours/destinations/shigatse/2.avif',
                'images' => [
                    'tours/destinations/shigatse/1.jpg',
                    'tours/destinations/shigatse/2.avif',
                    'tours/destinations/shigatse/3.png',
                    'tours/destinations/shigatse/4.jpg',
                    'tours/destinations/shigatse/5.jpg',
                ],
                'is_featured' => false,
            ],
            // ===================== SRI LANKA (5) =====================
            [
                'name' => 'Colombo',
                'country_id' => 5,
                'keywords' => 'tour',

                'short_description' => 'Commercial capital of Sri Lanka.',
                'content' => 'Colombo, Sri Lanka’s bustling capital, is a vibrant blend of modernity and history. Skyscrapers and contemporary shopping districts stand alongside colonial-era architecture, bustling markets, and serene temples. The city’s coastal setting offers a refreshing maritime breeze, while its lively streets reveal the rhythms of daily Sri Lankan life. From exploring heritage sites to savoring local cuisine and enjoying sunset views along the ocean, Colombo provides a dynamic introduction to the island’s culture and charm.',
                'type' => 'city',
                'latitude' => '6.9271',
                'longitude' => '79.8612',
                'cover_image' => 'tours/destinations/colombo/2.jpg',
                'images' => [
                    'tours/destinations/colombo/1.jpg',
                    'tours/destinations/colombo/2.jpg',
                    'tours/destinations/colombo/3.webp',
                    'tours/destinations/colombo/4.webp',
                    'tours/destinations/colombo/5.webp',
                ],
                'is_featured' => true,
            ],
            [
                'name' => 'Kandy',
                'country_id' => 5,
                'keywords' => 'tour',

                'short_description' => 'Cultural capital of Sri Lanka.',
                'content' => 'Kandy, nestled amidst lush hills in central Sri Lanka, is a city of spiritual and natural beauty. Famous for the sacred Temple of the Tooth, Kandy is a hub of Buddhist tradition and vibrant cultural performances. Surrounded by scenic lakes, terraced gardens, and misty hills, visitors can stroll through peaceful streets, witness local festivals, and soak in the serene ambiance that makes Kandy a harmonious blend of nature, spirituality, and heritage.',
                'type' => 'heritage',
                'latitude' => '7.2906',
                'longitude' => '80.6337',
                'cover_image' => 'tours/destinations/kandy/4.jpg',
                'images' => [
                    'tours/destinations/kandy/1.jpg',
                    'tours/destinations/kandy/2.jpg',
                    'tours/destinations/kandy/3.jpg',
                    'tours/destinations/kandy/4.jpg',
                    'tours/destinations/kandy/5.jpg',
                ],
                'is_featured' => true,
            ],
            [
                'name' => 'Sigiriya',
                'country_id' => 5,
                'keywords' => 'tour',

                'short_description' => 'Ancient rock fortress.',
                'content' => 'Sigiriya, often called the “Lion Rock,” is a marvel of history and natural beauty rising dramatically from the central plains. This UNESCO World Heritage site captivates with its ancient rock fortress, frescoes, and elaborate gardens. Visitors can climb the rock for panoramic views, explore the archaeological wonders, and wander through verdant surroundings, experiencing the perfect blend of adventure, culture, and timeless landscapes.',
                'type' => 'heritage',
                'latitude' => '7.9570',
                'longitude' => '80.7603',
                'cover_image' => 'tours/destinations/sigiriya/3.jpg',
                'images' => [
                    'tours/destinations/sigiriya/1.jpeg',
                    'tours/destinations/sigiriya/2.jpg',
                    'tours/destinations/sigiriya/3.jpg',
                    'tours/destinations/sigiriya/4.jpeg',
                    'tours/destinations/sigiriya/5.webp',
                ],
                'is_featured' => true,
            ],
            [
                'name' => 'Ella',
                'country_id' => 5,
                'keywords' => 'tour',

                'short_description' => 'Scenic hill town.',
                'content' => 'Ella, a tranquil hill town in Sri Lanka’s southern highlands, is a haven of misty mountains, tea plantations, and cascading waterfalls. The town’s laid-back charm invites visitors to hike scenic trails, visit iconic viewpoints like Little Adam’s Peak, and enjoy the fresh mountain air. With its lush greenery and peaceful atmosphere, Ella offers a rejuvenating escape immersed in nature’s serenity.',
                'type' => 'hill',
                'latitude' => '6.8667',
                'longitude' => '81.0466',
                'cover_image' => 'tours/destinations/ella/2.webp',
                'images' => [
                    'tours/destinations/ella/1.jpg',
                    'tours/destinations/ella/2.webp',
                    'tours/destinations/ella/3.jpg',
                    'tours/destinations/ella/4.jpg',
                    'tours/destinations/ella/5.jpg',
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'Galle',
                'country_id' => 5,
                'keywords' => 'tour',

                'short_description' => 'Historic coastal city.',
                'content' => 'Galle, a historic coastal city, is renowned for its iconic fort, cobblestone streets, and colonial-era architecture. Overlooking the Indian Ocean, the city blends rich cultural heritage with vibrant seaside life. Visitors can wander through boutique shops, explore museums, and admire sunset views from the fort walls, all while soaking in the timeless charm of Sri Lanka’s coastal history.',
                'type' => 'heritage',
                'latitude' => '6.0535',
                'longitude' => '80.2210',
                'cover_image' => 'tours/destinations/galle/3.jpg',
                'images' => [
                    'tours/destinations/galle/1.webp',
                    'tours/destinations/galle/2.jpg',
                    'tours/destinations/galle/3.jpg',
                    'tours/destinations/galle/4.jpg',
                    'tours/destinations/galle/5.jpg',
                ],
                'is_featured' => false,
            ],
            [
                'name' => 'Yala National Park',
                'country_id' => 5,
                'keywords' => 'tour',
                'short_description' => 'Wildlife safari destination.',
                'content' => 'Yala, a vast national park in southeastern Sri Lanka, is a paradise for wildlife enthusiasts and nature lovers. Home to elephants, leopards, exotic birds, and diverse flora, the park offers thrilling safari experiences through open plains, dense forests, and waterholes. With its pristine natural landscapes and rich biodiversity, Yala promises an adventurous and unforgettable connection with Sri Lanka’s wild beauty.',
                'type' => 'wildlife',
                'latitude' => '6.3667',
                'longitude' => '81.5167',
                'cover_image' => 'tours/destinations/yala/2.jpg',
                'images' => [
                    'tours/destinations/yala/1.jpg',
                    'tours/destinations/yala/2.jpg',
                    'tours/destinations/yala/3.jpg',
                    'tours/destinations/yala/4.jpg',
                    'tours/destinations/yala/5.jpg',
                ],
                'is_featured' => false,
            ],
        ];

        foreach ($destinations as $destination) {
            DB::table('destinations')->insert([
                'name' => $destination['name'],
                'country_id' => $destination['country_id'],
                'short_description' => $destination['short_description'],
                'keywords' => $destination['keywords'],
                'content' => $destination['content'],
                'slug' => Str::slug($destination['name']),
                'type' => $destination['type'],
                'latitude' => $destination['latitude'],
                'longitude' => $destination['longitude'],
                'cover_image' => $destination['cover_image'],
                'images' => json_encode($destination['images']),
                'status' => true,
                'is_featured' => $destination['is_featured'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
